image:
  repository: harbor.space.com/ibp/energy
  pullPolicy: IfNotPresent
  tag: ""


####### 环境变量
FrontAddress:
  - name: portalUrl
    value: http://portal-gateway-sit.space.com
  - name: baseUrl
    value: http://gateway-web.sit.svc.spaceiot.local:8000
  - name: ibpUrl
    value: http://ibp-gateway-web.sit.svc.spaceiot.local:8000
  - name: iframeUrl
    value: http://spaas-sit.space.com
  - name: messageUrl
    value: http://message-gateway.sit.svc.public.local:8550
  - name: messageWs
    value: http://message-channel-sit.space.com
  - name: uploadUrl
    value: http://gateway-web.sit.svc.spaceiot.local:8000
  - name: vedioUrl
    value: http://gateway-web.sit.svc.spaceiot.local:8000
  - name: spaceUrl
    value: http://portal-gateway-sit.space.com/space/v1
  - name: workOrderUrl
    value: http://spaas-sit.space.com
  - name: parkingUrl
    value: http://ibp-gateway-web.sit.svc.spaceiot.local:8000
  - name: spaasFlowUrl
    value: http://spaas-sit.space.com
BackendApiUrl: []




ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: spaceiot-sit.space.com
      paths:
        - path: /energy
          pathType: ImplementationSpecific
  tls: []


