##########################################################################################################
#                   作者：何梦飞
#                   编撰日期：2022年5月24日21点17分
#                   服务：ubmp-auth
#                   环境：prod
#                   端口说明：
#                       1. 注册端口：8071
#                       2. 调度端口：20884
#                   代码仓库地址：  http://gitlab.space.com/upms/ubmp/service/space-ubmp-auth.git                                                               #
#                   nacos地址：
#                       1. redis.yml,db-space.yml,nacos.yml,space.yml,common.yml,portal-env.yml
#                   域名地址： null
#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# 修改模块选择：
#       1.deployment.yaml
#       2.ingress.yaml
#       3.service.yaml
#
############################################################ deployment.yaml ##########################################
replicaCount: 1
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》  镜像定义
image:
  repository: harbor.space.com/iot/iot-data
  pullPolicy: IfNotPresent
  tag: "latest"
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》 是否开启边车模式 skywalking?
InitContainers:
  Enabled: false
  InitContainersMountsAttributes:
    - name: sw-agent-sidecar
      image: harbor.space.com/middleware/skywalking-agent:8.1.0
      imagePullPolicy: IfNotPresent
      command: ['sh']
      args: ['-c','mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent']
      volumeMounts:
        - mountPath: /skywalking/agent
          name: sw-agent
  ContainersMountsAttributes:
    - mountPath: /usr/skywalking/agent
      name: sw-agent
  VolumesAttributes:
    - name: sw-agent
      emptyDir: {}
# 》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》 - 是否开启镜像认证
ImagePullSecrets:
  Enabled: false
  Attributes:
    - name: dasdad
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》---  是否开启资源限制
resources:
  Enabled: false
  ResourcesAttributes:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》--- 是否开启健康检查
HealthCheck:
  Enabled: false
  EetectAttributes:
    startupProbe:
      failureThreshold: 50
      httpGet:
        path: /actuator/health
        port: registry
        scheme: HTTP
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /actuator/health
        port: registry
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /actuator/health
        port: registry
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》--- 是否开启污点
Tolerations:
  Enabled: false
  TolerationsAttributes:
    - key: "middleware"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》---  定义pord的端口
Deployment:
  Enabled: true
  Ports:
    - name: schedule
      containerPort: 18110
      protocol: TCP
    - name: registry
      containerPort: 8110
      protocol: TCP
######################################################## service.yaml #######################
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》-- 是否开启 链路兼容
Servicecompatible:
  Enabled: false
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》-- 是否开启 ClusterIP 网络IP
ClusterIPService:
  Enable: true
  type: ClusterIP
  ApplicationPort: 8110
  ClusterExternalPorts:
    - portName: schedule
      port: 18110
      targetPort: schedule
      protocol: TCP
    - portName: registry
      protocol: TCP
      port: 8110
      targetPort: registry
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》-- 是否开 NodePort 网络类型
NodePortService:
  Enable: false
  type: NodePort
  ClusterExternalPorts:
    - portName: Security
      protocol: TCP
      port: 443
      targetPort: Security
    - portName: schedule
      protocol: TCP
      port: 23398
      targetPort: schedule
    - portName: registry
      protocol: TCP
      port: 3398
      targetPort: registry
      nodePort: 30001
#》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》- LoadBalancer 网络类型
LoadBalancerPortService:
  Enable: false
  type: LoadBalancer
  ClusterExternalPorts:
    - portName: encryption
      port: 443  # 开启pod端口
      protocol: TCP
      targetPort: encryption # 开启pod映射到容器内部的端口
    - portName: schedule
      port: 23398  # 开启pod端口
      targetPort: schedule # 开启pod映射到容器内部的端口
      protocol: TCP
    - portName: registry
      port: 3398  # 开启pod端口
      targetPort: registry # 开启pod映射到容器内部的端口
      protocol: TCP
      nodePort: 30001


#############################################  ingress.yaml    #######################################################
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local



########################################## 业务环境 变量 统一配置 #################
#说明：修改变量如下：
#  EnvironmentAnnotations
#  EnvironmentGlobal
#  EnvironmentSidecar
#  EnvironmentCharacteristic
#  EnvironmentPublic
#  EnvironmentInterface
#》》》》》》》》》》》》》》》》》》》注解：EnvironmentAnnotations ：唯一环境标识符号，代表着是哪个环境，属于那个业务线
EnvironmentAnnotations:
  ServiceBusinessLine: iot
  ServiceEnvironment: test
  ServiceName: iot-data
#》》》》》》》》》》》》》》》》》》》》》》》》全局环境变量：EnvironmentGlobal{{$env}} #$env：部署环境
EnvironmentGlobal:
  - name: nacos-server-addr
    value: nacos-hs.middleware-test.svc.spaceiot.local:8848
  - name: nacos-namespace
    value:  iot
#》》》》》》》》》》》》》》》》》》》》》》》》》边车模式环境变量：EnvironmentSidecar
EnvironmentSidecar: []
#  - name: JAVA_OPTS
#    value: "-javaagent:/usr/skywalking/agent/skywalking-agent.jar"
#  - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
#    value: "skywalking-oap.skywalking.svc.portal.local:11800"
#  - name: SW_AGENT_NAME
#    value: V3-PROD
#  - name: SW_AGENT_AUTHENTICATION
#    value: "tsw_site@example"
#》》》》》》》》》》》》》》》》》》》》》》 特性接口环境变量：EnvironmentCharacteristic
EnvironmentCharacteristic: []
#》》》》》》》》》》》》》》》》》》》》》》》》》》》 中级间环境变量：EnvironmentPublic
EnvironmentPublic:
  - name: MysqlUrl
    value: "172.16.163.118"
  - name: MysqlPort
    value: "3317"
  - name: MysqlUsername
    value: root
  - name: MysqlPassword
    value: vtunf9iHZfkf9D_3JzzZ
  - name: RedisUrl
    value: ibp-redis-headless.middleware-test.svc.spaceiot.local
  - name: RedisPort
    value: "6379"
  - name: RedisPassword
    value: MWYyZDFlMmU2N2Rm
  - name: rocketmqUrl
    value: test-mq.space.com
  - name: rocketmqPort
    value: "9876"
  - name: ElasticsearchUrl
    value: elasticsearch-master.middleware-test.svc.public.local
  - name: ElasticsearchPort
    value: "9200"
  - name: ElasticsearchUsername
    value: "elastic"
  - name: ElasticsearchPassword
    value: "Wanzhu@sby!"
  - name: CassandraUrl
    value: "172.16.163.52"
  - name: CassandraPort
    value: "9042"
  - name: CloudEdgeMqNameServer
    value: test-mq.space.com:9876
  - name: CloudEdgeMqGroup
    value: cloud-edge-proxy-prodcuer-group
  - name: CloudEdgeMqTopic
    value: edge_belong_system_door_control
  - name: CloudEdgeSpaceUrl
    value: http://gateway-web.test.svc.spaceiot.local:8000
  - name: CloudEdgePropertyUrl
    value: http://osms-gateway-test.space.com
  - name: CloudEdgeIotUrl
    value: http://gateway-web.test.svc.spaceiot.local:8000
  - name: CloudEdgeTenementCode
    value: ZH_00098
  - name: CloudEdgeProjectCode
    value: ZH_00098_XM_00000001
#业务接口环境变量：EnvironmentInterface
nvironmentInterface:
  # 门户内网前端地址
  - name: portalUrl
    value: "https://portal-test.space.com"
  # 门户内网网关地址
  - name: portalAPIUrl
    value: "http://portal-gateway-test.space.com"
  # 门户外网前端地址
  - name: EportalUrl
    value: "https://portal-test.spaceplat.com"
  # 门户外网网关地址
  - name: EportalAPIUrl
    value: "https://portal-test.spaceplat.com"
  # 物联网内网前端地址
  - name: iotUrl
    value: "https://spaceiot-test.space.com"
  # 物联网内网网关地址
  - name: iotAPIUrl
    value: "https://iot-gateway-web-test.space.com"
  # 物联网外网前端地址
  - name: EiotUrl
    value: "https://spaceiot-test.spaceplat.com"
  # 物联网外网网关地址
  - name: EiotAPIUrl
    value: "https://iot-gateway-web-test.spaceplat.com"
  # 运营内网前端地址
  - name: osmsUrl
    value: "http://osms-test.space.com"
  # 运营内网网关地址
  - name: osmsAPIUrl
    value: "http://osms-gateway-test.space.com"
  # 运营外网前端地址
  - name: EosmsUrl
    value: "https://osms-test.spaceplat.com"
  # 运营外网网关地址
  - name: EosmsAPIUrl
    value: "https://osms-test.spaceplat.com"
  # spaas内网前端地址
  - name: spaasUrl
    value: "http://spaas-test.space.com"
  # spaas内网网关地址
  - name: spaasAPIUrl
    value: "http://spaas-gateway-test.space.com"
  # spaas外网前端地址
  - name: EspaasUrl
    value: "https://spaas-test.spaceplat.com"
  # spaas外网网关地址
  - name: EspaasAPIUrl
    value: "https://spaas-gateway-test.spaceplat.com"
  # 大数据内网前端地址
  - name: dataReportUrl
    value: "http://data-report-test.space.com"
  # 大数据内网网关地址
  - name: dataReportUrl
    value: "http://data-report-gateway-test.space.com"
  # 大数据外网前端地址
  - name: EdataReportUrl
    value: "https://data-report-test.spaceplat.com"
  # 大数据外网网关地址
  - name: EdataReportUrl
    value: "https://data-report-gateway-test.spaceplat.com"
  # 招商内网前端地址
  - name: investmentUrl
    value: "http://investment-test.space.com"
  # 招商内网网关地址
  - name: investmentAPIUrl
    value: "http://investment-gateway-test.space.com"
  # 招商外网前端地址
  - name: EinvestmentUrl
    value: "https://investment-test.spaceplat.com"
  # 招商外网网关地址
  - name: EinvestmentAPIUrl
    value: "https://investment-gateway-test.spaceplat.com"


##》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》》
###########################################################》》》》》》》》》》》》》》》》》》》》》》》
############################## 以下变量值 丢弃 ###########################################################################
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
affinity: {}
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
#  {{- if .Values.Deployment.Enable}}
#  {{- toYaml . | nindent 12 }}
#  {{- end }}
############################## 以上变量值 丢弃 ###########################################################################