replicaCount: 1

image:
  repository: space.tencentcloudcr.com/iot/api-manage
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

GlobalAttributes:
  - name: nacos-server-addr
    value: nacos-hs.middleware.svc.cluster.local:8848
  - name: nacos-namespace
    value: op
FrontAddress: []
BackendApiUrl: []
ExternalFrontAddress: []
ExternalBackendApiUrl: []
