replicaCount: 1

image:
  repository: space.tencentcloudcr.com/ibp/ibp-power
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

GlobalAttributes:
  - name: nacos-server-addr
    value: 10.122.144.36:31769
  - name: nacos-namespace
    value: ibp
FrontAddress: []
BackendApiUrl: []
ExternalFrontAddress: []
ExternalBackendApiUrl: []